### ISSUE TITLE
WeakMap key must be an Object

### ISSUE THREAD

**Issue by sampattuzzi** [xaviergonz/mobx-keystone#539] opened 2024-03-11 12:52 UTC
I'm using mobx-keystone in the context of a React Component. I've noticed that if I destructure the model, I get a really incompressible error message. Here is the code example that breaks (and fixes)
  
```
...
  const store = useStores()
  const {
    authenticationStore,
  } = store
  const { setAuthEmail } = authenticationStore

  useEffect(() => {
    // This causes the error.
    setAuthEmail("ignite@infinite.red")
    // This works just fine.
    // authenticationStore.setAuthEmail("ignite@infinite.red")
...
```

![image](https://github.com/xaviergonz/mobx-keystone/assets/1968960/e9318ca4-416f-40fd-a586-390d0ef2a6c4)

I'm just getting started with the stack, so let me know if I can get more useful errors of if you can't reproduce this yourself.

**Comment by xaviergonz** [comment] 2024-03-11 14:43
https://github.com/xaviergonz/mobx-keystone/issues/467#issue-1296479272

**Comment by xaviergonz** [comment] 2024-03-11 18:01
also duplicate of https://github.com/xaviergonz/mobx-keystone/issues/120

**Comment by sampattuzzi** [comment] 2024-03-11 19:23
Thanks, I tried to search the tickets but these didn’t come up for that
error message for some reason. Thanks for the swift reply.

**Closed** 2024-03-11 19:27 UTC
